###########################################
###########################################
##### CONFIG FOR DCASE CHALLENGE 2023 #####
###########################################
###########################################

##################################
# PARAMETERS FOR DATA PROCESSING #
##################################
data:
  n_task_train: 100
  n_task_val: 100
  target_fs: 16000
  resample: true
  denoise: true
  normalize: true
  frame_length: 25.0
  tensor_length: 128
  n_shot: 5
  n_query: 10
  overlap: 0.5
  n_subsample: 1 # ask Femke what this stands for
  status: train # train or validate or evaluate

#################################
# PARAMETERS FOR MODEL TRAINING #
#################################
# Be sure the parameters match the ones in data processing

trainer:
  max_epochs: 1
  default_root_dir: /data
  accelerator: gpu
  gpus: 1

model:
  distance: euclidean # other option is mahalanobis
  lr: 1.0e-05
  model_path: /data/BEATs/BEATs_iter3_plus_AS2M.pt # Or FOR INFERENCE: /data/lightning_logs/version_X/checkpoints/epoch=X-step=1500.ckpt
  specaugment_params: null
  # specaugment_params:
  #   application_ratio: 1.0
  #   time_mask: 40  
  #   freq_mask: 40 

##################################################################
# PARAMETERS FOR RUNNING THE TRAINED MODEL ON THE EVALUATION SET #
##################################################################

