###########################################
###########################################
##### CONFIG FOR DCASE CHALLENGE 2023 #####
###########################################
###########################################

##################################
# PARAMETERS FOR DATA PROCESSING #
##################################
data:
  n_task_train: 500
  n_task_val: 500
  target_fs: 16000 # used in preprocessing
  resample: True # used in preprocessing
  denoise: True # used in preprocessing
  normalize: true # used in preprocessing
  frame_length: 25.0 # used in preprocessing
  tensor_length: 128 # used in preprocessing
  n_shot: 3 # number of images PER CLASS in the support set
  n_query: 2 # number of images PER CLASS in the query set
  n_way: 20
  overlap: 0.5 # used in preprocessing
  n_subsample: 1 
  num_mel_bins: 128 # used in preprocessing
  max_segment_length: 1.0 # used in preprocessing
  status: train # used in preprocessing, train or validate or evaluate
  

#################################
# PARAMETERS FOR MODEL TRAINING #
#################################
# Be sure the parameters match the ones in data processing

trainer:
  max_epochs: 500
  default_root_dir: /data
  accelerator: gpu
  gpus: 1

model:
  distance: euclidean # other option is mahalanobis
  lr: 1.0e-05
  model_type: beats # beats, pann or baseline
  state: train # train or validate - for which model should be loaded
  model_path:  /data/DCASE/models/BEATs/BEATs_iter3_plus_AS2M.pt
  specaugment_params: null
  n_way: 20
  # specaugment_params:
  #   application_ratio: 1.0
  #   time_mask: 40  
  #   freq_mask: 40 