###########################################
###########################################
##### CONFIG FOR DCASE CHALLENGE 2023 #####
###########################################
###########################################

##################################
# PARAMETERS FOR DATA PROCESSING #
##################################
data:
  n_task_train: 100
  n_task_val: 100
  target_fs: 16000
  resample: true
  denoise: true
  normalize: true
  frame_length: 25.0
  tensor_length: 128
  n_shot: 5
  n_query: 10
  overlap: 0.5
  n_subsample: 1 # ask Femke what this stands for
  status: validate # train or validate or evaluate
  set_type: Validation_Set # Training_Set or Validation_Set or Evaluation_Set

#################################
# PARAMETERS FOR MODEL TRAINING #
#################################
# Be sure the parameters match the ones in data processing

trainer:
  max_epochs: 1
  default_root_dir: /data
  accelerator: gpu
  gpus: 1

model:
  distance: euclidean # other option is mahalanobis
  lr: 1.0e-05
  model_path: /data/lightning_logs/version_0/checkpoints/epoch=14-step=1500.ckpt # /data/BEATs/BEATs_iter3_plus_AS2M.pt # Or FOR INFERENCE: /data/lightning_logs/version_X/checkpoints/epoch=X-step=1500.ckpt


##################################################################
# PARAMETERS FOR RUNNING THE TRAINED MODEL ON THE EVALUATION SET #
##################################################################

