###########################################
###########################################
##### CONFIG FOR DCASE CHALLENGE 2023 #####
###########################################
###########################################

##################################
# PARAMETERS FOR DATA PROCESSING #
##################################
data:
  n_task_train: 100
  n_task_val: 100
  target_fs: 16000
  resample: true
  denoise: true # should the data be denoised using spectral gating https://github.com/timsainb/noisereduce
  normalize: true
  frame_length: 25.0
  tensor_length: 128 # used to extract a random segment of length $tensor_length out of the mel-spec of a positive sample
  n_shot: 5
  n_query: 10
  overlap: 0.5
  n_subsample: 1 # 
  status: validate # train or validate or evaluate

#################################
# PARAMETERS FOR MODEL TRAINING #
#################################
# Be sure the parameters match the ones in data processing

trainer:
  max_epochs: 5 # number of epochs to train the model on
  default_root_dir: /data/lightning_logs/pann # folder that contains all the logs
  accelerator: gpu
  gpus: 1

model:
  distance: euclidean # other option is mahalanobis
  lr: 1.0e-05
  model_type: beats # beats, pann or baseline
  state: None # train or validate or None if using beats or baseline // since we remove from layers from the original PANN we can't load the ckpts normally (see _build_model in prototraining.py)
  model_path: /data/lightning_logs/version_96/checkpoints/epoch=85-step=8600.ckpt #/data/lightning_logs/pann/lightning_logs/version_1/checkpoints/epoch=99-step=10000.ckpt #/data/lightning_logs/pann/lightning_logs/version_1/checkpoints/epoch=99-step=10000.ckpt #/data/model/PANN/Cnn14_mAP=0.431.pth # /data/model/BEATs/BEATs_iter3_plus_AS2M.pt #   # Or FOR INFERENCE: /data/lightning_logs/version_X/checkpoints/epoch=X-step=1500.ckpt
  specaugment_params: null
  # specaugment_params:
  #   application_ratio: 1.0
  #   time_mask: 40  
  #   freq_mask: 40 

##################################################################
# PARAMETERS FOR RUNNING THE TRAINED MODEL ON THE EVALUATION SET #
##################################################################

