###########################################
###########################################
##### CONFIG FOR DCASE CHALLENGE 2023 #####
###########################################
###########################################

##################################
# PARAMETERS FOR DATA PROCESSING #
##################################
data:
  n_task_train: 100
  n_task_val: 100
  target_fs: 16000 # used in preprocessing
  resample: True # used in preprocessing
  denoise: True # used in preprocessing
  normalize: True # used in preprocessing
  frame_length: 25.0 # used in preprocessing
  tensor_length: 128 # used in preprocessing
  n_shot: 3
  n_query: 2
  overlap: 0.5 # used in preprocessing
  n_subsample: 1 
  num_mel_bins: 128 # used in preprocessing
  max_segment_length: 1.0 # used in preprocessing
  status: validate # used in preprocessing, train or validate or evaluate
  set_type: "Validation_Set"
  

#################################
# PARAMETERS FOR MODEL TRAINING #
#################################
# Be sure the parameters match the ones in data processing
# Otherwise the hash of the folders will be different!!

trainer:
  max_epochs: 20
  default_root_dir: /data
  accelerator: gpu
  gpus: 1

model:
  distance: euclidean # other option is mahalanobis
  lr: 1.0e-05
  model_type: beats # beats, pann or baseline
  state: train # train or validate - for which model should be loaded
  model_path: None
  specaugment_params: null
  # specaugment_params:
  #   application_ratio: 1.0
  #   time_mask: 40  
  #   freq_mask: 40 

###################################
# PARAMETERS FOR MODEL PREDICTION #
###################################
predict:
  wav_save: False
  overwrite: True
  n_self_detected_supports: 0
  tolerance: 0
  filter_by_p_values: False # Whether we filter outliers by their pvalues
  n_subsample: 1 # Whether each segment should be subsampled
  self_detect_support: True # Whether to use the self-training loop
  threshold_p_value: 0.1

plot:
  tsne: True
  perplexity: 5
