#############
# Data path #
#############
save_dir: "/data/"
status: "validate"

####################
# Model parameters #
####################
model_path: "/app/lightning_logs/version_88/checkpoints/epoch=19-step=2000.ckpt"

##################################
# Prediction segments parameters #
##################################
overlap: 0.5

#########################
# DataLoader parameters #
#########################
batch_size: 16
num_workers: 8 # TODO check if actually used